title: MantaPro - rodrigoec19
email: rodrigo.dev@tuta.io
description: Manta es asi... # this means to ignore newlines until "baseurl:"
 Este es un blog de imágenes e información de la ciudad de Manta.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.mantapro.tk" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: rodrigoec19 # add your name
author-pic: avatarman.png
about-author: Estudiante  •  Autodidacta  •  Nunca debe faltar la buena música  • ...

# Contact links
email: rodrigo.dev@tuta.io # Add your Email address
phone: # Add your Phone number
website: www.rodrigoec19.tk # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: rodrigoec19 # Add your Github handle
twitter: '@rodrigoec19' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: rodrigoec19 # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
